### ISSUE TITLE
I found a translation error

### ISSUE THREAD

**Issue by qq5341** [KonoTyran/KonoTyran.github.io#1]
If you translate this word, it will display a non-existent English word

![Y6E}XE24QA{1Y@KUFY71DT2](https://user-images.githubusercontent.com/57039455/163315244-123c8420-7e7d-4bc7-8f08-9c246aa6c185.png)

![0IH(5V4 B` _G4N }AK9M%K](https://user-images.githubusercontent.com/57039455/163315375-bda786d7-208b-4e89-82ba-8e27440d6403.png)

I don't know if it's a person's name

**Comment by KonoTyran** [comment]
"human readable" is not English words. It's just a more English grouping of letters rather than IPA symbols. The world in question is most likely "furnace"
